In [7]:
# Import test data 
import yfinance as yf
import pandas as pd

dataF = yf.download("EURUSD=X",  start="2024-03-17", end="2024-04-17", interval='15m')
dataF.iloc[:,:]
#dataF.Open.iloc

[*********************100%%**********************]  1 of 1 completed

                         Open      High       Low     Close  Adj Close  Volume
Datetime
2024-03-18 00:00:00  1.088613  1.088613  1.088376  1.088613   1.088613       0
2024-03-18 00:15:00  1.088732  1.088969  1.088732  1.088969   1.088969       0
2024-03-18 00:30:00  1.088969  1.089087  1.088850  1.088850   1.088850       0
2024-03-18 00:45:00  1.088969  1.089087  1.088850  1.088850   1.088850       0
2024-03-18 01:00:00  1.088850  1.088969  1.088850  1.088850   1.088850       0
...                       ...       ...       ...       ...        ...     ...
2024-04-16 22:45:00  1.062135  1.062248  1.062022  1.062135   1.062135       0
2024-04-16 23:00:00  1.062135  1.062135  1.061571  1.061797   1.061797       0
2024-04-16 23:15:00  1.061909  1.062022  1.061909  1.061909   1.061909       0
2024-04-16 23:30:00  1.061909  1.061909  1.061797  1.061797   1.061797       0
2024-04-16 23:45:00  1.061684  1.062248  1.061684  1.062135   1.062135       0

[2080 rows x 6 columns]

In [8]:
def signal_generator(df):
    open = df.Open.iloc[-1]
    close = df.Close.iloc[-1]
    previous_open = df.Open.iloc[-2]
    previous_close = df.Close.iloc[-2]

    # Bearish Pattern
    if (open > close and
            previous_open < previous_close and
            close < previous_open and
            open >= previous_close):
        return 1

    # Bullish Pattern
    elif (open < close and
            previous_open > previous_close and
            close > previous_open and
            open <= previous_close):
        return 2

    # No clear pattern
    else:
        return 0

signal = []
signal.append(0)
for i in range(1,len(dataF)):
    df = dataF[i-1:i+1]
    signal.append(signal_generator(df))
#signal_generator(data)
dataF["signal"] = signal

In [9]:
dataF.signal.value_counts()
# dataF.iloc[:,:]

signal
0    1944
2      74
1      62
Name: count, dtype: int64